# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ilr_basis_default <- function(dim) {
    .Call('coda_base_ilr_basis_default', PACKAGE = 'coda.base', dim)
}

ilr_basis_simplex <- function(dim) {
    .Call('coda_base_ilr_basis_simplex', PACKAGE = 'coda.base', dim)
}

ilr_to_alr <- function(dim) {
    .Call('coda_base_ilr_to_alr', PACKAGE = 'coda.base', dim)
}

clr_coordinates <- function(X) {
    .Call('coda_base_clr_coordinates', PACKAGE = 'coda.base', X)
}

inv_clr_coordinates <- function(clrX) {
    .Call('coda_base_inv_clr_coordinates', PACKAGE = 'coda.base', clrX)
}

coordinates <- function(X, B) {
    .Call('coda_base_coordinates', PACKAGE = 'coda.base', X, B)
}

coordinates_default <- function(X) {
    .Call('coda_base_coordinates_default', PACKAGE = 'coda.base', X)
}

inv_ilr_coordinates <- function(ilrX) {
    .Call('coda_base_inv_ilr_coordinates', PACKAGE = 'coda.base', ilrX)
}

