# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinv <- function(X) {
    .Call(`_coda_base_pinv`, X)
}

c_variation_array <- function(X, only_variation = FALSE) {
    .Call(`_coda_base_c_variation_array`, X, only_variation)
}

alr_basis_default <- function(dim) {
    .Call(`_coda_base_alr_basis_default`, dim)
}

clr_basis_default <- function(dim) {
    .Call(`_coda_base_clr_basis_default`, dim)
}

ilr_basis_default <- function(dim) {
    .Call(`_coda_base_ilr_basis_default`, dim)
}

ilr_basis_simplex <- function(dim) {
    .Call(`_coda_base_ilr_basis_simplex`, dim)
}

ilr_to_alr <- function(dim) {
    .Call(`_coda_base_ilr_to_alr`, dim)
}

clr_coordinates <- function(X) {
    .Call(`_coda_base_clr_coordinates`, X)
}

inv_clr_coordinates <- function(clrX) {
    .Call(`_coda_base_inv_clr_coordinates`, clrX)
}

alr_coordinates <- function(X, denominator) {
    .Call(`_coda_base_alr_coordinates`, X, denominator)
}

matrix_coordinates <- function(X, B) {
    .Call(`_coda_base_matrix_coordinates`, X, B)
}

coordinates_basis <- function(X, B, sparse = FALSE) {
    .Call(`_coda_base_coordinates_basis`, X, B, sparse)
}

ilr_coordinates <- function(X) {
    .Call(`_coda_base_ilr_coordinates`, X)
}

inv_ilr_coordinates <- function(ilrX) {
    .Call(`_coda_base_inv_ilr_coordinates`, ilrX)
}

find_PB_rnd_local_search <- function(M, rep = 1L) {
    .Call(`_coda_base_find_PB_rnd_local_search`, M, rep)
}

find_PB_pc_local_search <- function(X) {
    .Call(`_coda_base_find_PB_pc_local_search`, X)
}

find_PB_log <- function(lX) {
    .Call(`_coda_base_find_PB_log`, lX)
}

find_PB <- function(X) {
    .Call(`_coda_base_find_PB`, X)
}

find_PB2 <- function(M, random = 100L, optim = 0L) {
    .Call(`_coda_base_find_PB2`, M, random, optim)
}

find_PB3 <- function(M, steps, random = 100L, optim = 0L, k = 0L) {
    .Call(`_coda_base_find_PB3`, M, steps, random, optim, k)
}

find_PB4 <- function(M) {
    .Call(`_coda_base_find_PB4`, M)
}

find_PB5 <- function(X) {
    .Call(`_coda_base_find_PB5`, X)
}

arma_sampling_without_replacement <- function(n, k) {
    .Call(`_coda_base_arma_sampling_without_replacement`, n, k)
}

